<?php
    /**
     * @Thomas-Athanasiou
     *
     * @author Thomas Athanasiou {thomas@hippiemonkeys.com}
     * @link https://hippiemonkeys.com
     * @link https://github.com/Thomas-Athanasiou
     * @copyright Copyright (c) 2022 Hippiemonkeys Web Inteligence EE All Rights Reserved.
     * @license http://www.gnu.org/licenses/ GNU General Public License, version 3
     * @package Hippiemonkeys_ModificationCodazonProductLabel
     */

	$object = $block->getObject();
	$labels = $object['labels'];
    $product = $object['product'];
	$imgHelper = $this->helper('Codazon\ProductLabel\Helper\Image');
	$objectManager = $this->getObjectManager();
	$filterObject = $objectManager->get('Magento\Framework\DataObject');
	$htmlFilter = $objectManager->get('Hippiemonkeys\ModificationCodazonProductLabel\Model\Filter');
	$filterObject->setData('product', $product);
?>
<ul class="cdz-product-labels">
	<?php foreach($labels as $label): ?>
		<?php
			$style = $label->getCustomCss();
			$filterObject->setData('text', $label->getContent());
			if($label->getLabelBackground())
			{
				$style .= \sprintf(
					'background-image:url(%s);',
					(string) $imgHelper->init($label->getLabelBackground())
				);
			}
			if($label->getLabelImage())
			{
				$image = (string) $imgHelper->init($label->getLabelImage());
			}
			$style .= $label->getCustomCss();
			$class = $label->getCustomClass();
		?>
		<li class="label-item <?php echo $class ?>" style="<?php echo $style ?>" >
			<div class="label-content">
				<?php if(isset($image)): ?>
				<img src="<?php echo $image ?>" />
				<?php endif ?>
				<?php echo $htmlFilter->filterLabel($filterObject) ?>
			</div>
		</li>
    <?php endforeach ?>
</ul>